### ISSUE TITLE
admin和admin server都下载并运行，还是报错，登录不了，麻烦给出详情的运行步骤，以便项目能正常运行起来。谢谢！

### ISSUE THREAD

**Issue by gezi11** [caiya/vuejs-admin-server#10]
![1](https://user-images.githubusercontent.com/26268994/56334175-e7653080-61c9-11e9-9772-2889fb515ca7.png)
![2](https://user-images.githubusercontent.com/26268994/56334211-05cb2c00-61ca-11e9-9c6a-7e0f15184fc5.png)

**Comment by gezi11** [comment]
admin和admin server都下载并运行，还是报错，登录不了，麻烦给出详情的运行步骤，以便项目能正常运行起来。谢谢！

**Comment by aYu-live** [comment]
server打开不了报错404

**Comment by simplettton** [comment]
admin server执行npm run dev报错555
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! oauthcenter@1.0.0 dev: `egg-bin dev`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the oauthcenter@1.0.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by ma1953** [comment]
server打开不了报错404

**Comment by caiya** [comment]
已经修改了，请拉去最新的客户端和服务端代码

**Comment by ma1953** [comment]
谢谢，明天试一试
