### ISSUE TITLE
中间件挂载?

### ISSUE THREAD

**Issue by reuwi** [caiya/vuejs-admin-server#5]
有个地方不是很明白,按照官方的文档,中间件挂载配置文件/config/config.default.js  导出的应该是个对象呀,为什么你导出的是个函数?

**Comment by caiya** [comment]
你说的是auth的中间件？具体可以看下eggjs官网，中间件部分，如何使用koa中间件

**Comment by reuwi** [comment]
@caiya 官网的是这样的,没有介绍导出函数的用法....
<br/>

<img src="https://i.loli.net/2018/05/21/5b02459c69000.png" alt="微信截图_20180521120037.png" title="微信截图_20180521120037.png" />

**Comment by reuwi** [comment]
额,找到了,在配置文件里面有介绍...
