### ISSUE TITLE
登录500错误是什么原因呢

### ISSUE THREAD

**Issue by hank2718** [caiya/vuejs-admin-server#9]
{"message":"Cannot read property 'secret' of undefined","stack":"TypeError: Cannot read property 'secret' of undefined\n    at AuthService.sign (/work/vuejs/vuejs-admin-server-master/app/service/auth.js:10:60)\n    at UsersController.login (/work/vuejs/vuejs-admin-server-master/app/controller/v1/users.js:31:37)\n    at <anonymous>","name":"TypeError","headers":{"Access-Control-Allow-Origin":"*"},"status":500}

**Comment by caiya** [comment]
可以试着把auth模块注释掉试试

**Comment by hank2718** [comment]
我就是来学习你的oauth是怎么实现的

**Comment by xuyangxy** [comment]
注释哪个地方呢 ?

**Comment by caiya** [comment]
已经修改了，请拉去最新的客户端和服务端代码
